blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ Discussion
    url: https://github.com/postify-repository/client/discussions
    about: ì§ˆë¬¸ì´ë‚˜ ì•„ì´ë””ì–´ê°€ ìˆìœ¼ì‹œë©´ Discussionì„ ì´ìš©í•´ì£¼ì„¸ìš”.
  - name: ğŸš€ Feature Request
    url: https://github.com/postify-repository/client/issues/new?template=feature.yml
    about: ìƒˆë¡œìš´ ê¸°ëŠ¥ ì¶”ê°€ë¥¼ ìš”ì²­í•  ë•Œ ì‚¬ìš©í•˜ì„¸ìš”.
  - name: ğŸ› Bug Report
    url: https://github.com/postify-repository/client/issues/new?template=bug.yml
    about: ë²„ê·¸ë¥¼ ë°œê²¬í–ˆì„ ë•Œ ì‹ ê³ í•´ì£¼ì„¸ìš”.
  - name: â™»ï¸ Refactoring
    url: https://github.com/postify-repository/client/issues/new?template=refactor.yml
    about: ì½”ë“œ ë¦¬íŒ©í† ë§ì´ í•„ìš”í•  ë•Œ ìš”ì²­í•˜ì„¸ìš”.
  - name: ğŸ“ Documentation
    url: https://github.com/postify-repository/client/issues/new?template=documentation.yml
    about: ë¬¸ì„œ ì‘ì„±ì´ë‚˜ ìˆ˜ì •ì´ í•„ìš”í•  ë•Œ ì‚¬ìš©í•˜ì„¸ìš”.
  - name: ğŸ”§ General Task
    url: https://github.com/postify-repository/client/issues/new?template=general.yml
    about: ì¼ë°˜ì ì¸ ì‘ì—… ìš”ì²­ ì‹œ ì‚¬ìš©í•˜ì„¸ìš”.
